name: Build/release
on: push
jobs:
  build:
    if: "contains(github.event.head_commit.message, '[build]')"
    runs-on: macos-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Build Electron app
        uses: samuelmeuli/action-electron-builder@36f2c8d70b897ccddf9b14c033ff24b94d66a23d
        with:
          github_token: ${{ secrets.github_token }}
      - run: mkdir -p dist/imgstash && cp dist/*.zip dist/imgstash
      - name: Upload Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: imgstash
          path: dist/imgstash
